### ISSUE TITLE
der decoder panic with some invalid input

### ISSUE THREAD

**Issue by qiujiangkun** [RustCrypto/formats#748]
```rust
use base64; // 0.13.1
use der::{Decoder, Sequence};

fn main() {
    let result = base64::decode("MEYCIQCpfzu0YLUP/Vuu3LBESRpGOa1jmH2LV1SzUe26QXlCpAIhANxNxNgulmAbiLgoUoqhPEy3e3JQMepXFlexMWOylc0N").unwrap();
    let seq: [u64; 2] = Decoder::new(result)
        .expect("Always success")
        .decode()
        .unwrap();
    
    println!("Seq {:?}", seq)
}

```
gives
```rust

source slice length (32) does not match destination slice length (8)
thread 'securosys::tests::test_recreate_key_and_sign_ed25519' panicked at 'source slice length (32) does not match destination slice length (8)', /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/asn1/integer/uint.rs:33:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/std/src/panicking.rs:556:5
   1: core::panicking::panic_fmt
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/panicking.rs:142:14
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/slice/mod.rs:3241:13
   3: core::slice::<impl [T]>::copy_from_slice
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/slice/mod.rs:3248:13
   4: der::asn1::integer::uint::decode_to_array
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/asn1/integer/uint.rs:33:5
   5: der::asn1::integer::<impl der::value::DecodeValue for u64>::decode_value
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/asn1/integer.rs:80:54
   6: <T as der::decodable::Decodable>::decode
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/decodable.rs:34:9
   7: der::decoder::Decoder::decode
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/decoder.rs:36:9
   8: <der::asn1::sequence_of::SequenceOf<T,_> as der::value::DecodeValue>::decode_value
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/asn1/sequence_of.rs:74:29
   9: der::asn1::sequence_of::<impl der::value::DecodeValue for [T; N]>::decode_value
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/asn1/sequence_of.rs:136:9
  10: <T as der::decodable::Decodable>::decode
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/decodable.rs:34:9
  11: der::decoder::Decoder::decode
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/der-0.5.1/src/decoder.rs:36:9
  12: hsm_sdk::securosys::decode_ed25519_pkcs7_result2
             at ./securosys.rs:618:25
  13: hsm_sdk::securosys::tests::test_recreate_key_and_sign_ed25519::{{closure}}
             at ./securosys.rs:775:22
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/future/mod.rs:91:19
  15: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/future/future.rs:124:9
  16: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}::{{closure}}
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:240:62
  17: tokio::coop::with_budget::{{closure}}
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:106:9
  18: std::thread::local::LocalKey<T>::try_with
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/std/src/thread/local.rs:446:16
  19: std::thread::local::LocalKey<T>::with
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/std/src/thread/local.rs:422:9
  20: tokio::coop::with_budget
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:99:5
  21: tokio::coop::budget
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/coop.rs:76:5
  22: tokio::runtime::basic_scheduler::Inner<P>::block_on::{{closure}}
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:240:39
  23: tokio::runtime::basic_scheduler::enter::{{closure}}
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:349:29
  24: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/macros/scoped_tls.rs:61:9
  25: tokio::runtime::basic_scheduler::enter
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:349:5
  26: tokio::runtime::basic_scheduler::Inner<P>::block_on
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:230:9
  27: tokio::runtime::basic_scheduler::InnerGuard<P>::block_on
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:501:9
  28: tokio::runtime::basic_scheduler::BasicScheduler<P>::block_on
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/basic_scheduler.rs:186:24
  29: tokio::runtime::Runtime::block_on
             at /home/jack/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.1/src/runtime/mod.rs:461:46
  30: hsm_sdk::securosys::tests::test_recreate_key_and_sign_ed25519
             at ./securosys.rs:778:9
  31: hsm_sdk::securosys::tests::test_recreate_key_and_sign_ed25519::{{closure}}
             at ./securosys.rs:721:5
  32: core::ops::function::FnOnce::call_once
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/ops/function.rs:251:5
  33: core::ops::function::FnOnce::call_once
             at /rustc/57f097ea25f2c05f424fc9b9dc50dbd6d399845c/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by qiujiangkun** [comment]
Checked with der 0.6.0. The panic is gone.
